version: 2
updates:
  # Infrastructure
  ## GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    groups:
      gh-actions:
        #applies-to: version-updates
        patterns: ["*"]
    commit-message:
      prefix: "deps(ci)"

  ## Go dependencies
  - package-ecosystem: "gomod"
    directory: "/insights"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    groups:
      minor-updates:
        #applies-to: version-updates
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "deps(go-insights)"

  - package-ecosystem: "gomod"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    groups:
      minor-updates:
        #applies-to: version-updates
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "deps(go-server)"

  - package-ecosystem: "gomod"
    directory: "/common"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    groups:
      minor-updates:
        #applies-to: version-updates
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "deps(go-common)"

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    groups:
      minor-updates:
        #applies-to: version-updates
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "deps(go-tools)"
